### ISSUE TITLE
Priority 1: Error with the "Active?" switch 

### ISSUE THREAD

**Issue by MagicalMS** [dustin-s/gamma#20] opened 2022-09-07 22:13 UTC
The "Active?" switch is just changing what buttons show on the POI description page on both the admin and user sides. 

1. Logged in
2. Selected a trail with a POI
3. Selected a POI
4. Turned “Active?” switch off
5. Pressed “Save and Close”
6. Logged out 
7. Selected same trail 
8. Saw POI was still there 
9. Selected POI 
10. Saw “Save and Close” there
11. Logged in
12. Found and selected same POI
13. Turned “Active?” switch on
14. Logged out again to see change
15. Repeated multiple times on different POI - all were in Kentucky 

Device is a Pixel 3 XL

(Image is what the user sees.) 
![Screenshot_20220907-170501](https://user-images.githubusercontent.com/88515183/188992332-20cd118d-b44a-44af-9347-219c318f7766.png)

**Comment by Chip-L** [comment] 2022-09-11 01:34
I cannot reproduce this. screen. How did you get here? Please type out the steps to reproduce.

**Comment by MagicalMS** [comment] 2022-09-11 02:26
1. Logged in
2. Selected a trail with a POI
3. Selected a POI
4. Turned “Active?” switch off 
5. Pressed “Save and Close”
6. Logged out 
7. Selected same trail
8. Saw POI was still there 
9. Selected POI 
10. Saw “Save and Close” there 
11. Logged in
12. Found and selected same POI
13. Turned “Active?” switch on
14. Logged out again to see change
15. Repeated multiple times on different POI - all were in Kentucky

Device was a Pixel 3 XL

**Comment by Chip-L** [comment] 2022-09-12 04:13
I've made progress on this... However this is a, "one step forward, three steps backwards" situation. 
I fixed so that the POIs don't display when they are inactive and the user is not logged in. This is the first half of this issue.
The second part is the POI is always dirty when it is inactive. There were a couple of things happening here:    
   - The state of the component wasn't being set and stored properly. 
   - The component wasn't being added to the trailsList properly so it wasn't updating on the main trail screen.

I have the first part fixed, but I'm having troubles with the second part. I also started getting the error where I can't save images again. To try to fix this, I moved the savePOI functionality into the POI screen (out of Admin Buttons -- where it didn't really belong anyways). I refactored the TrailListReducer so that I can add a POI to the trail. Right now, that reducer isn't working (I'm getting a dup ID error...) -- and I still can't save the image. I'll  try to continue on this more tomorrow night.
Chip Long Phone (Cell): 720-289-4751 

    On Saturday, September 10, 2022 at 08:27:06 PM MDT, MagicalMS ***@***.***> wrote:  
 
 

   
   - Logged in
   - Selected a trail with a POI
   - Selected a POI
   - Turned “Active?” switch off
   - Pressed “Save and Close”
   - Logged out
   - Selected same trail
   - Saw POI was still there
   - Selected POI
   - Saw “Save and Close” there
   - Logged in
   - Found and selected same POI
   - Turned “Active?” switch on
   - Logged out again to see change
   - Repeated multiple times on different POI - all were in Kentucky

Device was a Pixel 3 XL

**Comment by Chip-L** [comment] 2022-10-09 19:20
Fixed in the refactor POI branch.

**Closed as completed** 2022-10-10 23:07 UTC
